### ISSUE TITLE
menubar item is black 

### ISSUE THREAD

**Issue by maxwell108** [Pixel-Master/File-Find#10]
not good for dark theme cant see

**Comment by Pixel-Master** [comment]
Thank you for your issue, are talking about Windows or Linux? As this isn't an issue with macOS

**Comment by Pixel-Master** [comment]
and could you please provide a screenshot

**Comment by Pixel-Master** [comment]
Okay, i think it only happens on Linux/Windows now fixed aba5656

**Comment by maxwell108** [comment]
Yes, on Linux, its barley visible, latest version 
![Screenshot_2024-07-27_08-23-10](https://github.com/user-attachments/assets/ad4017bc-3f88-4583-8b9d-97dee183bbfb)

**Comment by Pixel-Master** [comment]
Fixed in File Find 1.1 https://github.com/Pixel-Master/File-Find/releases/tag/v1.1 or https://pixel-master.github.io/File-Find/download#1.1
